### ISSUE TITLE
pickling error of signal SIGSEGV

### ISSUE THREAD

**Issue by leonqli** [WojciechMula/pyahocorasick#97]
terminated by signal SIGSEGV (Address boundary error)

**Comment by WojciechMula** [comment]
I'm sorry you had problems. Could you please provide more details?

**Comment by leonqli** [comment]
This code is listed below. The file (t.txt) is a file containing 28 millions lines of text. 
```python
import pickle
import ahocorasick
A = ahocorasick.Automaton()
with open("t.txt") as f:
    for line in f:
        line = line.strip("\n")
        A.add_word(line, 1)
print("loaded")
with open ("t.pkl", 'wb') as f:
    print("begin to pickle")
    pickle.dump(A, f)
    print("finish")
```
The output: 
```bash
loaded
begin to pickle
fish: Job 1, 
```
and t.pkl is empty.

**Comment by WojciechMula** [comment]
@leonqli 28 million of lines means huge data. I'm afraid you hit #50, which is unresolved yet. It's almost fixed, but I need a few days to release it.

**Comment by leonqli** [comment]
Thanks! Please keep up with the great work!

**Comment by WojciechMula** [comment]
@leonqli If you can, please check the latest version. The bug I mentioned was fixed.

**Comment by WojciechMula** [comment]
@leonqli ping? did you have a chance to test a newer release?

**Comment by leonqli** [comment]
Just saw your message. I had a test just now. Unfortunately, it is still the same (empty t.pkl) ...

**Comment by pombredanne** [comment]
@leonqli gentle ping... this has been opened a couple years now without a reply so I am closing this. Please reopen with a reproducible test case if you still have the issue with the latest version.
